INSERT INTO USERS(USERNAME, EMAIL, PASSWORD)
VALUES('TIAGO', 'TIAGO@GMAIL.COM', 'ASDF')
VALUES('TESTE1', 'TESTE1@GMAIL.COM', 'ASDF')
VALUES('TESTE2', 'TESTE2@GMAIL.COM', 'ASDF')
VALUES('TESTE3', 'TESTE3@GMAIL.COM', 'ASDF');

INSERT INTO PROJECTS(PROJECT_NAME, OWNER_ID) VALUES
('PROJETO TIAGO', (SELECT USERS.USER_ID FROM USERS WHERE USERS.USERNAME = 'TIAGO')),
('PROJETO TESTE1', (SELECT USERS.USER_ID FROM USERS WHERE USERS.USERNAME = 'TESTE1')),
('PROJETO TESTE2', (SELECT USERS.USER_ID FROM USERS WHERE USERS.USERNAME = 'TESTE2')),
('PROJETO TESTE3', (SELECT USERS.USER_ID FROM USERS WHERE USERS.USERNAME = 'TESTE3'));

INSERT INTO BOARDS(BOARD_NAME, PROJECT_ID) VALUES
('BOARD TIAGO', (SELECT PROJECTS.PROJECT_ID FROM PROJECTS WHERE PROJECTS.PROJECT_NAME = 'PROJETO TIAGO')),
('BOARD TIAGO2', (SELECT PROJECTS.PROJECT_ID FROM PROJECTS WHERE PROJECTS.PROJECT_NAME = 'PROJETO TIAGO')),
('BOARD TIAGO3', (SELECT PROJECTS.PROJECT_ID FROM PROJECTS WHERE PROJECTS.PROJECT_NAME = 'PROJETO TIAGO')),

('BOARD TESTE1 TESTE1', (SELECT PROJECTS.PROJECT_ID FROM PROJECTS WHERE PROJECTS.PROJECT_NAME = 'PROJETO TESTE1')),
('BOARD TESTE1 TESTE2', (SELECT PROJECTS.PROJECT_ID FROM PROJECTS WHERE PROJECTS.PROJECT_NAME = 'PROJETO TESTE1')),
('BOARD TESTE1 TESTE3', (SELECT PROJECTS.PROJECT_ID FROM PROJECTS WHERE PROJECTS.PROJECT_NAME = 'PROJETO TESTE1')),

('BOARD TESTE2 TESTE1', (SELECT PROJECTS.PROJECT_ID FROM PROJECTS WHERE PROJECTS.PROJECT_NAME = 'PROJETO TESTE2')),
('BOARD TESTE2 TESTE2', (SELECT PROJECTS.PROJECT_ID FROM PROJECTS WHERE PROJECTS.PROJECT_NAME = 'PROJETO TESTE2')),
('BOARD TESTE2 TESTE3', (SELECT PROJECTS.PROJECT_ID FROM PROJECTS WHERE PROJECTS.PROJECT_NAME = 'PROJETO TESTE2')),

('BOARD TESTE3 TESTE1', (SELECT PROJECTS.PROJECT_ID FROM PROJECTS WHERE PROJECTS.PROJECT_NAME = 'PROJETO TESTE3')),
('BOARD TESTE3 TESTE2', (SELECT PROJECTS.PROJECT_ID FROM PROJECTS WHERE PROJECTS.PROJECT_NAME = 'PROJETO TESTE3')),
('BOARD TESTE3 TESTE3', (SELECT PROJECTS.PROJECT_ID FROM PROJECTS WHERE PROJECTS.PROJECT_NAME = 'PROJETO TESTE3'));

-- Insert task types for 'PROJETO TIAGO'
INSERT INTO TASK_TYPES (PROJECT_ID, TASK_TYPE_NAME, TASK_TYPE_DESCRIPTION)
SELECT PROJECT_ID, 'Task (default)', '' FROM PROJECTS WHERE PROJECT_NAME = 'PROJETO TIAGO'
UNION ALL
SELECT PROJECT_ID, 'Bug', 'Identify and track software bugs for resolution' FROM PROJECTS WHERE PROJECT_NAME = 'PROJETO TIAGO'
UNION ALL
SELECT PROJECT_ID, 'Milestone', '' FROM PROJECTS WHERE PROJECT_NAME = 'PROJETO TIAGO'
UNION ALL
SELECT PROJECT_ID, 'Request', 'Handle incoming requests or tasks from clients or team members' FROM PROJECTS WHERE PROJECT_NAME = 'PROJETO TIAGO';

-- Insert task types for 'PROJETO TESTE1'
INSERT INTO TASK_TYPES (PROJECT_ID, TASK_TYPE_NAME, TASK_TYPE_DESCRIPTION)
SELECT PROJECT_ID, 'Task (default)', '' FROM PROJECTS WHERE PROJECT_NAME = 'PROJETO TESTE1'
UNION ALL
SELECT PROJECT_ID, 'Bug', 'Identify and track software bugs for resolution' FROM PROJECTS WHERE PROJECT_NAME = 'PROJETO TESTE1'
UNION ALL
SELECT PROJECT_ID, 'Milestone', '' FROM PROJECTS WHERE PROJECT_NAME = 'PROJETO TESTE1'
UNION ALL
SELECT PROJECT_ID, 'Request', 'Handle incoming requests or tasks from clients or team members' FROM PROJECTS WHERE PROJECT_NAME = 'PROJETO TESTE1';

-- Insert task types for 'PROJETO TESTE2'
INSERT INTO TASK_TYPES (PROJECT_ID, TASK_TYPE_NAME, TASK_TYPE_DESCRIPTION)
SELECT PROJECT_ID, 'Task (default)', '' FROM PROJECTS WHERE PROJECT_NAME = 'PROJETO TESTE2'
UNION ALL
SELECT PROJECT_ID, 'Bug', 'Identify and track software bugs for resolution' FROM PROJECTS WHERE PROJECT_NAME = 'PROJETO TESTE2'
UNION ALL
SELECT PROJECT_ID, 'Milestone', '' FROM PROJECTS WHERE PROJECT_NAME = 'PROJETO TESTE2'
UNION ALL
SELECT PROJECT_ID, 'Request', 'Handle incoming requests or tasks from clients or team members' FROM PROJECTS WHERE PROJECT_NAME = 'PROJETO TESTE2';

-- Insert task types for 'PROJETO TESTE3'
INSERT INTO TASK_TYPES (PROJECT_ID, TASK_TYPE_NAME, TASK_TYPE_DESCRIPTION)
SELECT PROJECT_ID, 'Task (default)', '' FROM PROJECTS WHERE PROJECT_NAME = 'PROJETO TESTE3'
UNION ALL
SELECT PROJECT_ID, 'Bug', 'Identify and track software bugs for resolution' FROM PROJECTS WHERE PROJECT_NAME = 'PROJETO TESTE3'
UNION ALL
SELECT PROJECT_ID, 'Milestone', '' FROM PROJECTS WHERE PROJECT_NAME = 'PROJETO TESTE3'
UNION ALL
SELECT PROJECT_ID, 'Request', 'Handle incoming requests or tasks from clients or team members' FROM PROJECTS WHERE PROJECT_NAME = 'PROJETO TESTE3';

-- Insert tasks for 'BOARD TIAGO' in 'PROJETO TIAGO'
INSERT INTO TASKS (BOARD_ID, TASK_NAME, DESCRIPTION, TASK_TYPE_ID)
SELECT b.BOARD_ID,
       CONCAT('Task for ', b.BOARD_NAME, ' - ', tt.TASK_TYPE_NAME) AS TASK_NAME,
       CONCAT('This is a task of type ', tt.TASK_TYPE_NAME, ' for board ', b.BOARD_NAME) AS DESCRIPTION,
       tt.TASK_TYPE_ID
FROM BOARDS b
JOIN PROJECTS p ON b.PROJECT_ID = p.PROJECT_ID
JOIN TASK_TYPES tt ON tt.PROJECT_ID = p.PROJECT_ID
WHERE p.PROJECT_NAME = 'PROJETO TIAGO';

-- Insert tasks for 'PROJETO TESTE1'
INSERT INTO TASKS (BOARD_ID, TASK_NAME, DESCRIPTION, TASK_TYPE_ID)
SELECT b.BOARD_ID,
       CONCAT('Task for ', b.BOARD_NAME, ' - ', tt.TASK_TYPE_NAME) AS TASK_NAME,
       CONCAT('This is a task of type ', tt.TASK_TYPE_NAME, ' for board ', b.BOARD_NAME) AS DESCRIPTION,
       tt.TASK_TYPE_ID
FROM BOARDS b
JOIN PROJECTS p ON b.PROJECT_ID = p.PROJECT_ID
JOIN TASK_TYPES tt ON tt.PROJECT_ID = p.PROJECT_ID
WHERE p.PROJECT_NAME = 'PROJETO TESTE1';

-- Insert tasks for 'PROJETO TESTE2'
INSERT INTO TASKS (BOARD_ID, TASK_NAME, DESCRIPTION, TASK_TYPE_ID)
SELECT b.BOARD_ID,
       CONCAT('Task for ', b.BOARD_NAME, ' - ', tt.TASK_TYPE_NAME) AS TASK_NAME,
       CONCAT('This is a task of type ', tt.TASK_TYPE_NAME, ' for board ', b.BOARD_NAME) AS DESCRIPTION,
       tt.TASK_TYPE_ID
FROM BOARDS b
JOIN PROJECTS p ON b.PROJECT_ID = p.PROJECT_ID
JOIN TASK_TYPES tt ON tt.PROJECT_ID = p.PROJECT_ID
WHERE p.PROJECT_NAME = 'PROJETO TESTE2';

-- Insert tasks for 'PROJETO TESTE3'
INSERT INTO TASKS (BOARD_ID, TASK_NAME, DESCRIPTION, TASK_TYPE_ID)
SELECT b.BOARD_ID,
       CONCAT('Task for ', b.BOARD_NAME, ' - ', tt.TASK_TYPE_NAME) AS TASK_NAME,
       CONCAT('This is a task of type ', tt.TASK_TYPE_NAME, ' for board ', b.BOARD_NAME) AS DESCRIPTION,
       tt.TASK_TYPE_ID
FROM BOARDS b
JOIN PROJECTS p ON b.PROJECT_ID = p.PROJECT_ID
JOIN TASK_TYPES tt ON tt.PROJECT_ID = p.PROJECT_ID
WHERE p.PROJECT_NAME = 'PROJETO TESTE3';
